### ISSUE TITLE
Áreas de Atuação - Corrigir cards de serviços

### ISSUE THREAD

**Issue by kelvin-quadros** [lulaluano/brc-advogados#13]
- Atualizar margens entre os cards para no mínimo 30 pontos;
- Padronizar tamanho dos cards conforme modelo;
- Ajustar prévia de conteúdo conforme protótipo (texto e quebra de linhas);
- Ajustar títulos e dispor em uma única linha (no caso do "empresarial/pro..." deixar no card somente "Direito Empresarial");
- Adicionar hover no botão Ler Mais (Icone e Animação).

Modelo de hover disposição e tamanho dos cards:

![image](https://user-images.githubusercontent.com/80045167/112969370-8f5c3600-9123-11eb-9450-797e41db44e7.png)

**Comment by luangelsdorf** [comment]
- Texto da prévia nos cards é mostrado com base nos textos da página da Áreas de Atuação. Seria necessário criar um campo no CMS para devidamente ajustar os textos dos cards
